package generator

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"html/template"
	"path/filepath"

	"github.com/studiowebux/minimaldoc/static-generator/internal/core"
)

// I18nGenerator generates localized documentation output
type I18nGenerator struct {
	site      *core.Site
	templates *template.Template
	themeFS   embed.FS
	version   string // MinimalDoc version
}

// LocalesJSON is the structure for locales.json metadata file
type LocalesJSON struct {
	Current           string           `json:"current"`
	Default           string           `json:"default"`
	HideDefaultLocale bool             `json:"hideDefaultLocale"`
	Locales           []LocaleInfoJSON `json:"locales"`
}

// LocaleInfoJSON represents locale info in JSON output
type LocaleInfoJSON struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Direction string `json:"direction"`
	Flag      string `json:"flag,omitempty"`
	Active    bool   `json:"active"`
}

// NewI18nGenerator creates a new i18n generator
func NewI18nGenerator(site *core.Site, themeFS embed.FS, version string) (*I18nGenerator, error) {
	tmpl := template.New("").Funcs(OpenAPIFuncMap()).Funcs(MCPFuncMap()).Funcs(AnalyticsFuncMap())

	tmpl, err := tmpl.ParseFS(
		themeFS,
		"themes/common/templates/*.html",
		"themes/common/templates/partials/*.html",
	)
	if err != nil {
		return nil, fmt.Errorf("failed to parse common templates: %w", err)
	}

	return &I18nGenerator{
		site:      site,
		templates: tmpl,
		themeFS:   themeFS,
		version:   version,
	}, nil
}

// Generate generates localized documentation
func (g *I18nGenerator) Generate() error {
	if !g.site.Config.I18n.Enabled || len(g.site.Config.I18n.Locales) == 0 {
		return nil
	}

	fmt.Println("Generating localized documentation...")

	defaultLocale := g.site.Config.I18n.DefaultLocale
	if defaultLocale == "" && len(g.site.Config.I18n.Locales) > 0 {
		defaultLocale = g.site.Config.I18n.Locales[0].Code
	}

	// Generate pages for each locale (main pages)
	for _, localeInfo := range g.site.Config.I18n.Locales {
		pages, ok := g.site.LocalizedPages[localeInfo.Code]
		if !ok {
			continue
		}

		isDefaultLocale := localeInfo.Code == defaultLocale

		// Generate main pages for this locale
		if err := g.generateLocalePages(localeInfo, pages, isDefaultLocale, "", nil); err != nil {
			return fmt.Errorf("failed to generate locale %s: %w", localeInfo.Code, err)
		}

		fmt.Printf("  Generated locale %s (%s): %d pages\n", localeInfo.Code, localeInfo.Name, len(pages))

		// Generate versioned pages for this locale (if versioning enabled)
		if g.site.Config.Versions.Enabled && len(g.site.Config.Versions.List) > 0 {
			defaultVersionName := g.site.Config.Versions.Default
			if defaultVersionName == "" {
				defaultVersionName = g.site.Config.Versions.List[0].Name
			}

			for _, versionInfo := range g.site.Config.Versions.List {
				versionPages, ok := g.site.VersionedPages[versionInfo.Name]
				if !ok {
					continue
				}

				isDefaultVersion := versionInfo.Name == defaultVersionName

				// Skip default version for default locale (already generated by VersionGenerator)
				if isDefaultLocale && isDefaultVersion {
					continue
				}

				// For non-default locales, generate all versions under locale prefix
				// For default locale with non-default version, skip (handled by VersionGenerator)
				if isDefaultLocale && !isDefaultVersion {
					continue
				}

				// Get translation map for this locale
				translationMap := make(map[string]*core.Page)
				if localizedPages, ok := g.site.LocalizedPages[localeInfo.Code]; ok {
					for _, p := range localizedPages {
						translationMap[p.Slug] = p
					}
				}

				// Generate: /fr/v1.1/..., /fr/v1.0/..., etc.
				if err := g.generateLocaleVersionedPages(localeInfo, versionPages, versionInfo.Path, &versionInfo, translationMap); err != nil {
					return fmt.Errorf("failed to generate locale %s version %s: %w", localeInfo.Code, versionInfo.Name, err)
				}

				fmt.Printf("    Generated locale %s version %s: %d pages\n", localeInfo.Code, versionInfo.Name, len(versionPages))
			}
		}
	}

	// Generate locales.json metadata
	if err := g.generateLocalesJSON(defaultLocale); err != nil {
		return fmt.Errorf("failed to generate locales.json: %w", err)
	}

	return nil
}

// generateLocalePages generates HTML pages for a specific locale
func (g *I18nGenerator) generateLocalePages(localeInfo core.LocaleInfo, pages []*core.Page, isDefaultLocale bool, versionPath string, versionInfo *core.VersionInfo) error {
	basePath := g.getBasePath()

	// Skip default locale main pages if HideDefaultLocale is true (already handled by HTMLGenerator)
	if isDefaultLocale && g.site.Config.I18n.HideDefaultLocale && versionPath == "" {
		return nil
	}

	for _, page := range pages {
		// Build output path: [locale]/[version]/slug.html
		var outputPath string
		if isDefaultLocale && g.site.Config.I18n.HideDefaultLocale {
			// Default locale: /v1.1/slug.html (but this is handled by VersionGenerator)
			continue
		}
		// Non-default locale: /fr/slug.html or /fr/v1.1/slug.html
		if versionPath != "" {
			outputPath = filepath.Join(g.site.OutputRoot, localeInfo.Code, versionPath, page.Slug+".html")
		} else {
			outputPath = filepath.Join(g.site.OutputRoot, localeInfo.Code, page.Slug+".html")
		}

		// Determine current version for template
		var currentVersion *core.VersionInfo
		if versionInfo != nil {
			currentVersion = versionInfo
		} else if g.site.Config.Versions.Enabled && len(g.site.Config.Versions.List) > 0 {
			defaultVersionName := g.site.Config.Versions.Default
			if defaultVersionName == "" {
				defaultVersionName = g.site.Config.Versions.List[0].Name
			}
			currentVersion = g.site.Config.Versions.GetVersion(defaultVersionName)
		}

		// Prepare template data
		data := map[string]any{
			"Site":           g.site,
			"Page":           page,
			"Content":        template.HTML(page.HTML),
			"BasePath":       basePath,
			"Version":        g.version,
			"CurrentVersion": currentVersion,
			"CurrentLocale":  &localeInfo,
			"IsDefault":      isDefaultLocale,
			"LocalePrefix":   g.getLocalePrefix(localeInfo, isDefaultLocale),
			"Lang":           localeInfo.Code,
			"Dir":            localeInfo.GetDirection(),
		}

		// Execute template
		var buf bytes.Buffer
		if err := g.templates.ExecuteTemplate(&buf, "layout.html", data); err != nil {
			return fmt.Errorf("template execution failed for %s: %w", page.Slug, err)
		}

		// Create output directory
		outputDir := filepath.Dir(outputPath)
		if err := makeWebDir(outputDir); err != nil {
			return fmt.Errorf("failed to create output directory: %w", err)
		}

		// Write HTML file
		if err := writeWebFile(outputPath, buf.Bytes()); err != nil {
			return fmt.Errorf("failed to write file: %w", err)
		}
	}

	return nil
}

// generateLocaleVersionedPages generates versioned pages for a non-default locale, applying translations where available
func (g *I18nGenerator) generateLocaleVersionedPages(localeInfo core.LocaleInfo, pages []*core.Page, versionPath string, versionInfo *core.VersionInfo, translations map[string]*core.Page) error {
	basePath := g.getBasePath()

	for _, page := range pages {
		// Check if we have a translation for this page
		pageToRender := page
		if translation, ok := translations[page.Slug]; ok {
			// Use translated content but keep the page structure
			pageToRender = translation
		}

		// Build output path: /locale/version/slug.html
		outputPath := filepath.Join(g.site.OutputRoot, localeInfo.Code, versionPath, page.Slug+".html")

		// Prepare template data
		data := map[string]any{
			"Site":           g.site,
			"Page":           pageToRender,
			"Content":        template.HTML(pageToRender.HTML),
			"BasePath":       basePath,
			"Version":        g.version,
			"CurrentVersion": versionInfo,
			"CurrentLocale":  &localeInfo,
			"IsDefault":      false,
			"LocalePrefix":   "/" + localeInfo.Code,
			"Lang":           localeInfo.Code,
			"Dir":            localeInfo.GetDirection(),
		}

		// Execute template
		var buf bytes.Buffer
		if err := g.templates.ExecuteTemplate(&buf, "layout.html", data); err != nil {
			return fmt.Errorf("template execution failed for %s: %w", page.Slug, err)
		}

		// Create output directory
		outputDir := filepath.Dir(outputPath)
		if err := makeWebDir(outputDir); err != nil {
			return fmt.Errorf("failed to create output directory: %w", err)
		}

		// Write HTML file
		if err := writeWebFile(outputPath, buf.Bytes()); err != nil {
			return fmt.Errorf("failed to write file: %w", err)
		}
	}

	return nil
}

// generateLocalesJSON creates the locales.json metadata file
func (g *I18nGenerator) generateLocalesJSON(defaultLocale string) error {
	localesJSON := LocalesJSON{
		Current:           g.site.CurrentLocale,
		Default:           defaultLocale,
		HideDefaultLocale: g.site.Config.I18n.HideDefaultLocale,
		Locales:           make([]LocaleInfoJSON, 0, len(g.site.Config.I18n.Locales)),
	}

	for _, l := range g.site.Config.I18n.Locales {
		localesJSON.Locales = append(localesJSON.Locales, LocaleInfoJSON{
			Code:      l.Code,
			Name:      l.Name,
			Direction: l.GetDirection(),
			Flag:      l.Flag,
			Active:    l.Code == defaultLocale,
		})
	}

	data, err := json.MarshalIndent(localesJSON, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal locales.json: %w", err)
	}

	outputPath := filepath.Join(g.site.OutputRoot, "locales.json")
	if err := writeWebFile(outputPath, data); err != nil {
		return fmt.Errorf("failed to write locales.json: %w", err)
	}

	return nil
}

// getLocalePrefix returns the URL prefix for a locale
func (g *I18nGenerator) getLocalePrefix(localeInfo core.LocaleInfo, isDefault bool) string {
	if isDefault && g.site.Config.I18n.HideDefaultLocale {
		return ""
	}
	return "/" + localeInfo.Code
}

// getBasePath extracts the path component from BaseURL
func (g *I18nGenerator) getBasePath() string {
	return GetBasePath(g.site.Config.BaseURL)
}
