name: Publish Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "internal/assets/**"
      - "templates/**"
      - ".github/workflows/doc.yml"
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build MinimalDoc from source
        run: go build -o minimaldoc ./cmd/minimaldoc

      - name: Build static files
        id: build
        run: ./minimaldoc build docs -o public

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./public/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
